import wordfreq
import re
from collections import Counter
import database

# Common words to ignore
STOPWORDS = {
    'the', 'a', 'an', 'and', 'or', 'but', 'in', 'on', 'at', 'to', 'for',
    'of', 'with', 'by', 'from', 'as', 'is', 'was', 'are', 'were', 'be',
    'been', 'being', 'have', 'has', 'had', 'do', 'does', 'did', 'will',
    'would', 'should', 'could', 'may', 'might', 'must', 'can', 'this',
    'that', 'these', 'those', 'i', 'you', 'he', 'she', 'it', 'we', 'they',
    'what', 'which', 'who', 'when', 'where', 'why', 'how', 'all', 'each',
    'every', 'both', 'few', 'more', 'most', 'other', 'some', 'such', 'no',
    'nor', 'not', 'only', 'own', 'same', 'so', 'than', 'too', 'very', 's',
    't', 'just', 'don', 'now', 'said', 'his', 'her', 'their', 'my', 'your'
}

def score_word(word):
    #1. Rarity score (0-1, and rarer=higher)
    frequency = wordfreq.word_frequency(word,'en')
    rarity_score = 1-frequency

    #2. Length_score
    length_score = min(len(word)/12,1.0)

    #3. Syllable score
    syllables = count_syllables(word)
    syllable_score = min(syllables/5,1.0)

    #4. Morphological complexity penalty
    # Penalize common suffixes that don't add semantic complexity
    suffix_penalty = 0.0

    # Heavy penalty for adverb/gerund suffixes (just grammatical variations)
    if word.endswith(('ly', 'ing', 'ness', 'ment', 'ful', 'less')):
        suffix_penalty = 0.3  # Reduce score by 30%
    # Lighter penalty for noun suffixes (can still be complex concepts)
    elif word.endswith(('tion', 'sion', 'ance', 'ence', 'ity')):
        suffix_penalty = 0.15  # Reduce score by 15%

    # Calculate base score
    base_score = (0.77*rarity_score + 0.03*syllable_score + 0.1*length_score)

    # Apply suffix penalty
    final_score = base_score * (1 - suffix_penalty)

    return final_score

def count_syllables(word):

    word = word.lower().strip()

    if len(word) <= 1:
        return 1

    vowels = 'aeiouy'
    syllable_count = 0
    previous_was_vowel = False

    for i, char in enumerate(word):
        is_vowel = char in vowels

        if is_vowel and not previous_was_vowel:
            syllable_count += 1

        previous_was_vowel = is_vowel

    # Handle silent 'e' at the end
    if word.endswith('e') and syllable_count > 1:
        syllable_count -= 1

    # Handle special cases like "smiled" (should be 1, not 2)
    if word.endswith('le') and len(word) > 2 and word[-3] not in vowels:
        syllable_count += 1

    # Ensure at least 1 syllable
    return max(syllable_count, 1)

def extract_words(text):
    # Remove punctuation and convert to lowercase
    text = text.lower()
    # Extract words (only alphabetic characters)
    words = re.findall(r'\b[a-z]+\b', text)
    return words

def analyze_text(text):
    """
    Main function: analyzes text and returns top 3 complex words

    Args:
        text: Combined OCR text from book pages

    Returns:
        List of dicts with format:
        [
            {
                "word": "ambivalent",
                "definition": "",  # Will be filled by Claude later
                "example": "",      # Will be filled by Claude later
                "difficulty": 0.85
            },
            ...
        ]
    """
    # Extract all words
    all_words = extract_words(text)

    if not all_words:
        return []

    # Get excluded words from database (mastered + saved)
    excluded_words = database.get_excluded_words()
    print(f"Excluding {len(excluded_words)} words from database (mastered + saved)")

    # Filter out stopwords, short words, AND excluded words from database
    filtered_words = [
        word for word in all_words
        if word not in STOPWORDS and len(word) >= 4 and word not in excluded_words
    ]

    if not filtered_words:
        return []

    # Count word frequencies in the text (to avoid duplicates)
    word_freq = Counter(filtered_words)
    unique_words = list(word_freq.keys())

    # Score each unique word
    word_scores = []
    for word in unique_words:
        score = score_word(word)
        word_scores.append({
            'word': word,
            'score': score
        })

    # Sort by score (highest first) and take top 10 to let Claude HAiku do its thing.
    word_scores.sort(key=lambda x: x['score'], reverse=True)
    top_10 = word_scores[:10]

    # Format for API response
    results = []
    for item in top_10:
        results.append({
            'word': item['word'],
            'definition': 'Definition will be generated by Claude AI',
            'example': 'Feynman-style example coming soon!',
            'difficulty': round(item['score'], 2)
        })

    return results